PUPPET-123 Fix broken redirect to stderr

diff --git a/templates/usr/local/sbin/restore-postgresql-database.sh.erb b/templates/usr/local/sbin/restore-postgresql-database.sh.erb
--- a/templates/usr/local/sbin/restore-postgresql-database.sh.erb
+++ b/templates/usr/local/sbin/restore-postgresql-database.sh.erb
@@ -3,12 +3,12 @@
 # This file is managed by Puppet
 
 if [ -z "$1" ]; then
-  echo "usage: $0 <database>" 1>2&
+  echo "usage: $0 <database>" 1>&2
   exit 1
 fi
 
 if [ "$EUID" -ne "0" ]; then
-  echo "This script must be run as root." 1>2&
+  echo "This script must be run as root." 1>&2
   exit 2
 fi
 
@@ -19,6 +19,6 @@ ps cax | grep postgres > /dev/null
 if [ $? -eq 0 ]; then
   zcat "$DUMP_FILE" | sudo -i -u postgres psql --no-password -d "$DATABASE" -f -
 else
-  echo "PostgreSQL server not running - import of database ${DATABASE} aborted." 1>2&
+  echo "PostgreSQL server not running - import of database ${DATABASE} aborted." 1>&2
   exit 3
 fi
